import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar/Navbar";
import Footer from "./Component/Footer/Footer";

const manrope = Manrope({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${manrope.className} h-full antialiased`}
    >
      
      <body className=" bg-white min-h-full flex flex-col"><Navbar/>{children}  <Footer/>   </body>
    
    </html>
  );
}
